import { makeGame, join, steps, onHull } from './tests/helpers.ts';
import { quietAdv, advMap, guardShip, cardView, advView } from './server/src/game/advmap.ts';
import { runAdmin } from './server/src/game/admin.ts';
const { game } = makeGame();
quietAdv(game, false);
const conn = join(game, 'Tester');
const s = game.sessionByName('Tester')!;
onHull(game, s.ship!, 'brig', 5);
console.log(runAdmin(game, s, '/guard'));
console.log(runAdmin(game, s, '/guard go'));
steps(game, 60);
const m = advMap(game);
const near = m.guards.find(g => guardShip(game, g.id));
console.log('materialized', near?.id, near && guardShip(game, near.id)?.crew, near?.kind);
console.log(JSON.stringify(cardView(game, s)).slice(0, 600));
console.log(runAdmin(game, s, '/obj chest go'));
steps(game, 30);
console.log(JSON.stringify(cardView(game, s)).slice(0, 600));
console.log(runAdmin(game, s, '/obj well go'));
steps(game, 30);
const cv = cardView(game, s);
console.log(JSON.stringify(cv).slice(0, 400));
conn.push({ t: 'h4', action: 'visit', id: cv!.obj!.id });
console.log(conn.all('toast').slice(-2));
const v = advView(game, s); console.log('seen', v.objs.length, v.guards.length, v.pieces, v.of);
console.log(runAdmin(game, s, '/obelisk 8'));
console.log(runAdmin(game, s, '/grail'));
console.log(runAdmin(game, s, '/grail go'));
conn.push({ t: 'h4', action: 'dig' });
steps(game, 20 * 22);
console.log(conn.all('toast').slice(-3).map(t=>t.msg));
const pz = conn.last('puzzle'); console.log(pz?.view.n, pz?.view.coasts.length, pz?.view.found, pz?.view.held, pz?.view.region);
