"""The piers of every port painting as the keel strikes them (2026-10-09): one box per pier, as drawn.

A town's quays are the painting's foot (below 0.735 of its height), drawn out over the water at the shore
(client/src/render/renderer.ts drawPorts). The keel struck them as one box over the whole foot, the water between the
piers included. Here, down every column of the foot from the quay line, how far the quay holds without a break (the
quay wall, a pier, a boat moored alongside: what clear_quays.py keeps), in bins across the width; then each run of bins
of about one depth is a box, from the quay line down to its deepest. The water between two piers is water.

Writes shared/src/data/quays.ts (generated: re-run this, never hand-edit). No image is made or changed.

    python tools/art/quay_piers.py
"""

import json
import os

import numpy as np
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
QUAY = 0.735  # where the renderer's foot slice begins (a share of the height)
SOLID = 40  # alpha at or above: part of the quay
GAP = 4  # open water this many pixels long ends the quay in a column
BINS = 128  # across the width
MIN_RUN = 6  # a bin whose quay runs fewer pixels than this is water (a rope, a shadow's edge)
LEVEL = 0.1  # bins within this share of the foot's depth of each other are one box
MERGE = 0.07  # flush neighbours within this share of the height of each other's depth are one box
SHALLOW = 0.025  # a box shallower than this share of the height lies on the shore's band: no pier


def runs(path: str):
    im = Image.open(path).convert('RGBA')
    a = np.array(im)
    h, w = a.shape[:2]
    y0 = int(h * QUAY)
    alpha = a[y0:, :, 3] >= SOLID
    run = np.zeros(w, dtype=int)
    for x in range(w):
        col = alpha[:, x]
        gap = 0
        end = len(col)
        for i, solid in enumerate(col):
            if solid:
                gap = 0
                continue
            gap += 1
            if gap >= GAP:
                end = i - gap + 1
                break
        run[x] = end
    return run, h, w, y0


def boxes(path: str):
    run, h, w, y0 = runs(path)
    foot = h - y0
    edges = [round(i * w / BINS) for i in range(BINS + 1)]
    bins = [int(run[edges[i]:edges[i + 1]].max()) if edges[i + 1] > edges[i] else 0 for i in range(BINS)]
    out = []
    i = 0
    while i < BINS:
        if bins[i] < MIN_RUN:
            i += 1
            continue
        j = i
        lo = hi = bins[i]
        while j + 1 < BINS and bins[j + 1] >= MIN_RUN and max(hi, bins[j + 1]) - min(lo, bins[j + 1]) <= LEVEL * foot:
            j += 1
            lo, hi = min(lo, bins[j]), max(hi, bins[j])
        out.append([edges[i] / w, edges[j + 1] / w, hi / h])
        i = j + 1
    # Fewer, plainer boxes: a neighbour flush with it and within MERGE of its depth is one box with it (the deeper
    # depth: a pier's tapered end and a boat alongside are struck where drawn, a few metres of water given up); a stub
    # at the quay line itself (under SHALLOW of the height: the shore's band covers it) is no pier.
    merged = []
    for b in out:
        if merged and abs(merged[-1][1] - b[0]) < 1e-9 and abs(merged[-1][2] - b[2]) <= MERGE:
            merged[-1][1] = b[1]
            merged[-1][2] = max(merged[-1][2], b[2])
        else:
            merged.append(list(b))
    return [[round(a, 4), round(b, 4), round(d, 4)] for a, b, d in merged if d >= SHALLOW]


def main() -> None:
    with open(os.path.join(ROOT, 'assets', 'manifest.json'), encoding='utf-8') as fh:
        m = json.load(fh)
    table = {}
    for key, meta in sorted(m['assets'].items()):
        if not key.startswith('prop.port_') or key == 'prop.port_town':
            continue  # (the old stand-in is painted on its own water: no piers to find in it)
        path = os.path.join(ROOT, 'assets', meta['local'])
        if not os.path.exists(path):
            continue
        table[key] = boxes(path)
        print(key, len(table[key]), table[key])
    lines = [
        '// Generated by tools/art/quay_piers.py from the port paintings\' feet (2026-10-09): re-run it, never hand-edit.',
        '// Each painting\'s quays over the water as the keel strikes them, one box per pier and per stretch of quay wall:',
        '// [left, right, depth] — left and right as shares of the painting\'s width, depth below the quay line (QUAY_LINE of',
        '// its height, where the renderer\'s foot slice begins) as a share of its height. Between two boxes is water.',
        '',
        '/** Where the painting\'s foot (the quays) begins, as a share of its height (client/src/render/renderer.ts drawPorts). */',
        f'export const QUAY_LINE = {QUAY};',
        '',
        'export const QUAY_PIERS: Record<string, readonly (readonly [number, number, number])[]> = {',
    ]
    for key, bs in table.items():
        lines.append(f"  '{key}': [{', '.join(f'[{a}, {b}, {d}]' for a, b, d in bs)}],")
    lines.append('};')
    lines.append('')
    with open(os.path.join(ROOT, 'shared', 'src', 'data', 'quays.ts'), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(lines))
    print('wrote shared/src/data/quays.ts:', len(table), 'paintings')


if __name__ == '__main__':
    main()
