// Quick look: login and the captain choice at one size.  node tools/mobile/fit/peek.mjs 812 375 ru
import * as L from '../m0/lib.mjs';
import { readFileSync } from 'node:fs';
const FIT = readFileSync(new URL('./measure.js', import.meta.url), 'utf8');
const [W, H, lang] = [Number(process.argv[2] ?? 812), Number(process.argv[3] ?? 375), process.argv[4] ?? 'ru'];
const OUT = process.env.OUT ?? 'assets/raw/audit/fit';
const b = await L.browser();
const p = await L.page(b, [W, H], { lang });
await p.goto('http://localhost:58997', { waitUntil: 'domcontentloaded' });
await p.waitForSelector('#login-name', { state: 'visible', timeout: 90000 });
await L.sleep(1500);
const fit = async (root) => { await p.evaluate(FIT); return p.evaluate((r) => globalThis.__fit(r), root); };
await p.screenshot({ path: `${OUT}/peek_login_${W}x${H}_${lang}.png` });
console.log('login', JSON.stringify(await fit('#screen-login'), null, 1));
await p.fill('#login-name', 'Peek' + Math.random().toString(36).slice(2, 5));
await p.click('#login-form button');
await p.waitForSelector('#screen-captain:not(.hidden)', { timeout: 45000 });
await L.sleep(1500);
await p.screenshot({ path: `${OUT}/peek_captain_${W}x${H}_${lang}.png` });
console.log('captain', JSON.stringify(await fit('#screen-captain'), null, 1));
await b.close();
